version: '3.8'

services:
  mainline:
    build:
      context: ./app
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: 1.17.9-perl
        BUILD_FILE: debian.conf
    image: app:mainline

  stable:
    build:
      context: ./app
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: ${DEFAULT_NGINX_VERSION}
        BUILD_FILE: debian.conf
    image: app:${DEFAULT_NGINX_VERSION}

  alpine:
    build:
      context: ./app
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: 1.17.9-alpine-perl
        BUILD_FILE: alpine.conf
    image: app:alpine

